package com.lacouf.rsbjwt.model.Enum;

public enum SecteurActivite {
    INFORMATIQUE,
    PHARMACEUTIQUE,
    FINANCE,
    SANTE,
    EDUCATION,
    COMMERCE_DETAIL,
    COMMERCE_GROS,
    RESTAURATION_HOTELLERIE,
    CONSTRUCTION,
    IMMOBILIER,
    TRANSPORT_LOGISTIQUE,
    MANUFACTURE_INDUSTRIE,
    AGRICULTURE,
    MEDIAS_COMMUNICATION,
    AEROSPATIAL,
    ENERGIE,
    SERVICES_CONSEIL,
    ARTS_DIVERTISSEMENT,
    ADMINISTRATION_PUBLIQUE
}
