spring.application.name=ReactSpringSecurityJwt
spring.profiles.active=dev
# Configuration de la base de données PostgreSQL Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/projet
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configuration JWT
application.security.jwt.secret-key=2B7E151628AED2A6ABF7158809CF4F3C2B7E151628AED2A6ABF7158809CF4F3C
application.security.jwt.expiration=86400000

spring.h2.console.enabled=false

# Limite de taille pour les fichiers téléversés
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB